version: "3"

services:
  backend:
    build:
      context: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/backend

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

  mysql:
    build:
      context: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: stock_trading
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    ports:
      - 33066:3306

volumes:
  react_build:
  db_data:
